### ISSUE TITLE
PHP 8 compatibility?

### ISSUE THREAD

**Issue by 5833tP2** [Indexhibit/indexhibit#28]
Vaska, I'm raising this here rather than the forum because the forum is not accepting new postings. This is a critical problem and not just a "How do I ..." question.

My hosting service has just upgraded to PHP8 and my indexhibit 2.1.6 site has immediately stopped working. Browser generates this error: `[Domain] is currently unable to handle this request. HTTP ERROR 500 `

Does this require an update to indexhibit code, or is there a setting I can update myself? I'm no expert in php and am flying blind ... also slightly panicked.

**Comment by TandiRD** [comment]
Hi 5833tP2,

Did you find any solution to this? I've been spending two days trying to resolve the same issue looking at the Indexhibit forum, but I haven't found any solution and I've made too many attempts at changing so nothing works anymore.

Slightly panicked too :)
Thanks !
Trd

**Comment by 5833tP2** [comment]
No solution at all, I'm afraid @TandiRD. I got no response to my posting. In depseration, I migrated my site to another platform. I hated having to do it but there was no other option for me. You could try emailing Vaska directly at studio@vaska.com. Sorry I don't have better news.

**Comment by kees-** [comment]
This has happened to me over time, with various hosts deprecating EOL'ed PHP versions. I think I recall trying to get in touch with the devs directly as well. Tragically I decided to move away from indexhibit as it seems more or less retired by the devs. Unfortunate loss of an elegant and fun tool.

**Comment by TandiRD** [comment]
Thank you both @5833tP2 & @kees- for the fast reply! I'll try e-mailing Vaska and if not migrating to another site. That would be a pitty though, Indexhibit is such a good tool. I don't understand how the passage to php 8 could mess it all up. I thought it was an advantage to always have the last version.

**Comment by kees-** [comment]
The world of updating software architecture is not comparable to the end user experience, where updating to the latest app, the newest operating system, buying the newest phone is all generally safe practice.

Creating a piece of software involves depending on all sorts of _things_ related to computers. Nothing is ever created from scratch. Even the earliest calculating machines relied on stable formal systems: the laws of math, physics.. Think about how when you do something as simple as arithmetic, you're trusting that the rules of combining some numbers to get a new result haven't changed, because that would break your calculations. So back to computer science, the design process is about where you place your trust among a large stack of tools, rules, and systems that you must rely on. One thing, in one time and place, must do exactly what you command it to.

With the countless things needed to develop software in the modern environment, you need to organize collections of them as they exist in specific times and places. These are called your **dependencies**. Dependencies can be languages, libraries, frameworks etc, all the way down to hardware.

In contrast to the essentially stable rules of arithmetic, active software is constantly being updated by developers to work better and do more. Security and user experience are also omnipresent concerns.

The web is all over the place in that regard. Things developed so quickly that certain tools have now been nearly unchanged for decades, while other efforts big and small can be downright ramshackle. When there's no precedent in a space, all something has to do to be widely adopted is work well enough for now. For major software like PHP, cleaning it up later involves rewriting lots of code and patching problems that compromise the security of its dependents. Largely for that reason, versioning is used to sort out what will work in one time and place, and what won't.

All this is just to spell out why deprecation happens. Stuff can't always be backwards compatible. Sometimes the effort to keep up is semantic, but sometimes involves so much refactoring that it plays a significant role in devs retiring fading projects.


Vaska has written about letting go of indexhibit. I do believe its only chance would be if it was picked up (more likely, completely recreated) by new dev(s). I hope this answer isn't pandering, I just wanted to explain it comprehensively because you were curious.

**Comment by Indexhibit** [comment]
It's amazing how much people know about me. The projects fail because it takes time and money. Where were all of you when I was trying to find donations? How many have emailed me begging for free help - not offering to hire me or pay me for working on your personal site? It's totally unfair that I am responsible and underappreciated. Can you afford to work for over a decade for free? I simply can't. When I have time...I have time...this is the reality. I really do not appreciate that my personal email was posted in this thread...

**Comment by TandiRD** [comment]
@kees- I appreciate the comprehensive explanations. I was thinking it was something along those lines, but the forum incentivising php update got me confused.

@Indexhibit those are very fair and valid points, food for thought on internet and labor. For what it’s worth: thank you for all your work and time. I understand however that gratitude doesn’t pay the bills and will keep that in mind for the future.
