### ISSUE TITLE
Is Indexhibit dead?

### ISSUE THREAD

**Issue by maathieu** [Indexhibit/indexhibit#29]
Hi,

I've been contacted by an artist friend about migrating his indexhibit portfolio to wordpress so as to get a responsive version of his website. My first reflex was to go check on indexhibit.org whether there was new updates and possibly someone might have worked on responsive templates for indexhibit, but the front page of indexhibit.org is empty or nearly empty, and the last updates were done last year...

Maybe it's time to announce that the project is not maintained anymore?

An official announcement would allow people to start planning for a migration.

It was a lovely project btw, I loved working with it a few years back!

Best to you and thanks for everything,

maathieu

**Comment by giisha** [comment]
The author had mention it’s not being maintained due to exhaustion of resource: he was doing it for free anyway, and if you look at the earlier post, you’d understand you should not expect updates and supports. 

[said earlier post](https://github.com/Indexhibit/indexhibit/issues/28#issuecomment-1010635166) 

Then again if you need a responsive site you shouldn’t be looking at indexhibit, it is a platform designed from the time of simpler sites.

**Comment by maathieu** [comment]
Thanks for your answer. I hope the author can update the [Readme](https://github.com/Indexhibit/indexhibit) so that people can see straight away that the project is over :-).
