### ISSUE TITLE
v2.1.6 with PHP 8.0

### ISSUE THREAD

**Issue by laborissa** [Indexhibit/indexhibit#37]
Hello,
according to the the author, the version 2.1.6 should work fine, but when I switch my PHP version to 8.0, I get a blank front-end, while the back-end works fine.

**Comment by Indexhibit** [comment]
Yes, if you have upgraded to the files on this site it works well. What I have noticed though - and I have no idea what your the problem actually is on your site - some webhosts don't have the same set of PHP extensions enabled. Recently, I had to debug a site where the PHP version didn't even have the Mysqli extension on by default. You might look in to that - but it could be many things, as well (missing config file, malformed uploaded file, etc). Since this post doesn't involve an actual specific issue (which is how Github is supposed to work - for actual bugs), I'm going to close it.
